#!/bin/bash
echo "================================================"
echo "Quick PA-API Status Check"
echo "================================================"
echo ""
echo "1. Open your Associates Reports:"
echo "   https://affiliate-program.amazon.com/home/reports"
echo ""
echo "2. Check for:"
echo "   - Orders in last 30 days"
echo "   - Qualified Sales count"
echo "   - Items Shipped"
echo ""
echo "3. If you have < 10 sales:"
echo "   → That's why PA-API is returning 403"
echo "   → DealBot works with fallback prices"
echo "   → Generate sales to reactivate PA-API"
echo ""
echo "4. If you have >= 10 sales:"
echo "   → Contact Amazon Associates Support"
echo "   → Something else is wrong"
echo ""
echo "================================================"
echo "Meanwhile, your DealBot IS WORKING:"
echo "================================================"
echo ""
echo "✅ Prices from TXT files"
echo "✅ Affiliate links with retroshell00-20"
echo "✅ Can publish to WhatsApp"
echo "✅ Generating commissions"
echo ""
echo "⚠️  Only missing real-time price validation"
echo ""
