#!/bin/bash
# Interactive setup script for DealBot environment variables

set -e

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║           DealBot Environment Variables Setup                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "This script will help you configure your API keys."
echo "Press Enter to skip optional keys."
echo ""

# Check if .env exists and has content
if [ -f .env ] && [ -s .env ] && grep -q "=" .env; then
    echo "⚠️  WARNING: .env file already exists with content!"
    echo ""
    cat .env
    echo ""
    read -p "Do you want to OVERWRITE it? (yes/no): " overwrite
    if [ "$overwrite" != "yes" ]; then
        echo "Setup cancelled. Edit .env manually if needed."
        exit 0
    fi
fi

# Create .env file
cat > .env << 'EOF'
# DealBot Environment Variables
# Generated by setup_env.sh

EOF

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "REQUIRED: WhatsApp API (whapi.cloud)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
read -p "Enter WHAPI_API_KEY: " whapi_key
echo "WHAPI_API_KEY=$whapi_key" >> .env
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "REQUIRED: Amazon Product Advertising API"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
read -p "Enter AMAZON_PAAPI_ACCESS_KEY: " amazon_access
echo "AMAZON_PAAPI_ACCESS_KEY=$amazon_access" >> .env

read -p "Enter AMAZON_PAAPI_SECRET_KEY: " amazon_secret
echo "AMAZON_PAAPI_SECRET_KEY=$amazon_secret" >> .env

read -p "Enter AMAZON_ASSOCIATE_TAG: " amazon_tag
echo "AMAZON_ASSOCIATE_TAG=$amazon_tag" >> .env
echo "" >> .env

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "REQUIRED: Short Link Provider (Cloudflare or Bitly)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Choose one: (1) Cloudflare or (2) Bitly"
read -p "Enter choice (1 or 2): " provider_choice

if [ "$provider_choice" = "1" ]; then
    echo "# Cloudflare (selected)" >> .env
    read -p "Enter CLOUDFLARE_ACCOUNT_ID: " cf_account
    echo "CLOUDFLARE_ACCOUNT_ID=$cf_account" >> .env
    
    read -p "Enter CLOUDFLARE_API_TOKEN: " cf_token
    echo "CLOUDFLARE_API_TOKEN=$cf_token" >> .env
    echo "# BITLY_TOKEN=" >> .env
else
    echo "# Bitly (selected)" >> .env
    read -p "Enter BITLY_TOKEN: " bitly_token
    echo "BITLY_TOKEN=$bitly_token" >> .env
    echo "# CLOUDFLARE_ACCOUNT_ID=" >> .env
    echo "# CLOUDFLARE_API_TOKEN=" >> .env
fi
echo "" >> .env

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "OPTIONAL: Ratings Provider (press Enter to skip)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Optional: Ratings providers" >> .env

read -p "Enter KEEPA_API_KEY (optional): " keepa_key
if [ -n "$keepa_key" ]; then
    echo "KEEPA_API_KEY=$keepa_key" >> .env
else
    echo "# KEEPA_API_KEY=" >> .env
fi

read -p "Enter RAINFOREST_API_KEY (optional): " rainforest_key
if [ -n "$rainforest_key" ]; then
    echo "RAINFOREST_API_KEY=$rainforest_key" >> .env
else
    echo "# RAINFOREST_API_KEY=" >> .env
fi

read -p "Enter SERPAPI_KEY (optional): " serpapi_key
if [ -n "$serpapi_key" ]; then
    echo "SERPAPI_KEY=$serpapi_key" >> .env
else
    echo "# SERPAPI_KEY=" >> .env
fi

echo ""
echo "✅ Environment variables saved to .env"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Next steps:"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1. Review .env file: cat .env"
echo "2. Test locally: make run"
echo "3. Rebuild app: ./rebuild_app.sh"
echo ""
echo "The .env file will be automatically bundled in the macOS app."
echo ""
